spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:someone@gmail.com}
    password: ${PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true